volumes:
  reverse_proxy_data:
    driver: local
  reverse_proxy_config:
    driver: local

networks:
  oauth2_proxy_network:
  keycloak_db_network:
  reverse_proxy_network:

services:
  reverse-proxy:
    image: caddy/caddy:2.6.0-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - reverse_proxy_data:/data
      - reverse_proxy_config:/config
    restart: unless-stopped
    environment:
      - KEYCLOAK_PUBLIC_ADDRESS=${KEYCLOAK_PUBLIC_ADDRESS}
      - FOUNDRYVTT_PUBLIC_ADDRESS=${FOUNDRYVTT_PUBLIC_ADDRESS}
    ports:
      - "38080:80"
      - "38443:443"
    networks:
      - reverse_proxy_network

  keycloak-db:
    image: postgres:13.8
    restart: unless-stopped
    volumes:
      - ${KEYCLOAK_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_db_network

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    restart: unless-stopped
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY: edge
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/" ]
      interval: 5s
      timeout: 2s
      retries: 15
    volumes:
      - ./foundryvtt-theme:/opt/keycloak/themes/foundryvtt-theme:ro
    depends_on:
      keycloak-db:
        condition: service_healthy
    command:
      - start --db=postgres
    networks:
      - keycloak_db_network
      - reverse_proxy_network

  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    command: >
      --config /oauth2-proxy.cfg 
      --cookie-secret ${OAUTH2_PROXY_COOKIE_SEED} 
      --cookie-domain ${OAUTH2_PROXY_COOKIE_DOMAIN} 
      --whitelist-domain ${OAUTH2_PROXY_WHITELIST_DOMAIN}
      --client-id ${OAUTH2_PROXY_CLIENT_ID}
      --client-secret ${OAUTH2_PROXY_CLIENT_SECRET}
      --redirect-url ${OAUTH2_PROXY_REDIRECT_URL}
      --oidc-issuer-url ${OAUTH2_PROXY_OIDC_ISSUER_URL}
    hostname: oauth2-proxy
    volumes:
      - ./oauth2-proxy-keycloak.cfg:/oauth2-proxy.cfg
    restart: unless-stopped
    networks:
      - oauth2_proxy_network
      - reverse_proxy_network
    depends_on:
      keycloak:
          condition: service_healthy

  foundry-vtt:
    image: felddy/foundryvtt:9
    init: true
    volumes:
      - ${FOUNDRYVTT_DATA_PATH}:/data
    environment:
      - CONTAINER_CACHE=/data/container_cache
#      - FOUNDRY_RELEASE_URL=https://foundryvtt.s3.amazonaws.com/releases/9.X/FoundryVTT-9.X.zip?XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    restart: unless-stopped
    networks:
      - oauth2_proxy_network
